apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgraph-deployment
  namespace: agentgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentgraph
  template:
    metadata:
      labels:
        app: agentgraph
    spec:
      containers:
      - name: agentgraph
        image: <ACR_LOGIN_SERVER>/agentgraph:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
