apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-gradio-app
  namespace: default # or a specific namespace you create
spec:
  replicas: 1 # Start with one replica
  selector:
    matchLabels:
      app: rag-gradio-app
  template:
    metadata:
      labels:
        app: rag-gradio-app
    spec:
      containers:
      - name: rag-app
        image: placeholder-image-name # Will be filled in by GitHub Actions workflow
        imagePullPolicy: Always
        ports:
        - containerPort: 7860
        env:
          # CRITICAL: Pass secrets as environment variables.
          # These values will come from the Kubernetes Secret.
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: rag-secrets
                key: openai-api-key
          - name: TAVILY_API_KEY
            valueFrom:
              secretKeyRef:
                name: rag-secrets
                key: tavily-api-key

          - name: LANGCHAIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: rag-secrets
                key: langchain-api-key
          # Add any other configs (e.g., index name) here or in your app code
          # - name: PINECONE_INDEX_NAME
          #   value: "my-index"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"