apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgraph-deployment
  namespace: agentgraph
  labels:
    app: agentgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentgraph
  template:
    metadata:
      labels:
        app: agentgraph
    spec:
      containers:
        - name: agentgraph
          image: <ACR_LOGIN_SERVER>/agentgraph:${IMAGE_TAG}
          ports:
            - containerPort: 7860
          env:
            - name: PORT
              value: "7860"
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"
            - name: TAVILY_API_KEY
              value: "${TAVILY_API_KEY}"
            - name: LANGCHAIN_API_KEY
              value: "${LANGCHAIN_API_KEY}"


          livenessProbe:
            httpGet:
              path: /   # Gradio usually responds at root
              port: 7860
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 5
            periodSeconds: 10
